### ISSUE TITLE
Funderingsinformatie koppelen (of toevoegen) aan de BAG

### ISSUE THREAD

**Issue by mklompkadaster** [imbag/wensen#67]
Wens als mogelijke opvolging van het RLI-rapport Goed Gefundeerd:

https://www.rijksoverheid.nl/documenten/rapporten/2023/10/09/rli-advies-goed-gefundeerd

**Comment by martijnodijk** [comment]
Vanuit de VRO-directie Bouwen en Energie is er een wens om funderingsinformatie voor gebouwen in Nederland in te richten. Gaat enerzijds om informatie over funderingen die nu nog niet ontsloten wordt (maar bijv. wel bij een gemeente in een archief zit), anderzijds om een mogelijkheid dat gebouw-eigenaren funderingsinformatie vertrouwd kunnen delen. Hierbij kan gebruik gemaakt worden van de object-ID's in de BAG (zo koppel je funderingsinformatie op een juiste wijze aan de BAG). Als de informatie uit de funderingsdatabase ontsloten moet worden in combinatie met gegevens uit de BAG (bijv. bouwjaar) en BRO kan dat via een informatieproduct (met een betalende opdrachtgever).

Dit wordt in 2025 (waarschijnlijk) projectmatig opgepakt in een project tussen VRO/dgVB (Volkshuisvesting en Bouwen), VRO/RO (programma ZoNDF en BRO) en TNO/RGD (BRO) en Kadaster.

Issue kan hier gesloten en gearchiveerd worden.
